kind: Service
apiVersion: v1
metadata:
 name: nginx
spec:
  selector:
    version: "1.0"
    environment: prod
    project: expense
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    version: "1.0"
    environment: prod
    project: expense   
spec:
  containers:
  - name: nginx
    image: nginx



