kind: Service
apiVersion: v1
metadata: 
 name: Nginx-np
spec:
  type: NodePort
  selector:
    env: Dev
    project: expense
    version: "2.0"
  ports: 
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30017
---
kind: Pod
apiVersion: v1
metadata: 
 name: backend-np
 labels:
  env: Dev
  project: expense
  version: "2.0"
spec:
 containers:
 - name: nginx
   image: nginx