apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    project: expense
    component: backend
    environment: dev
    verison: "1.0"
  ports:
   - protocal: TCP
     port: 80
     target: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend-np
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0"
spec:
  containers:
  - name: nginx
    image: nginx
