kind: Service
apiVersion: v1
metadata: 
 name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    env: prod
    project: expense
    version: "3.0"
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30017
---
kind: Pod
apiVersion: v1
metadata: 
 name: backend-lb
 labels:
  env: prod
  project: expense
  version: "3.0"
spec:
 containers:
 - name: nginx
   image: nginx